package com.deedeedev.ytreader.data.local

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "subtitles",
    indices = [Index(value = ["videoId", "trackIdentity"], unique = true)]
)
data class SubtitleEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val videoId: String,
    val videoUrl: String = "",
    val title: String,
    val channelName: String = "", // Default for migration, though we'll likely clear DB
    val languageCode: String,
    val subtitleTrackId: String? = null,
    val isAutoGenerated: Boolean = false,
    val trackIdentity: String = if (!subtitleTrackId.isNullOrBlank()) {
        "track:${subtitleTrackId.trim()}:${if (isAutoGenerated) "auto" else "manual"}"
    } else {
        "lang:${languageCode.trim().ifBlank { "unknown" }.lowercase()}:${if (isAutoGenerated) "auto" else "manual"}"
    },
    val content: String,
    val studyContent: String? = null,
    val lastTimestamp: Long = 0L,
    val lastOpenedAt: Long = 0L,
    val lastStudyScroll: Int = 0,
    val fontSize: Float = 16f,
    val createdAt: Long = System.currentTimeMillis(),
    val uploadDate: Long = 0L,
    val fontFamily: String = "Default",
    val highlights: String = "",
    val aiCleaningInProgress: Boolean = false,
    val aiCleaningSourceText: String? = null,
    val aiCleaningPendingResult: String? = null,
    val aiCleaningErrorSummary: String? = null,
    val aiCleaningErrorLog: String? = null,
    val aiCleaningUpdatedAt: Long = 0L
)
