package com.deedeedev.ytreader.data.local

import android.content.Context
import android.database.Cursor
import androidx.room.Room
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.sqlite.db.SupportSQLiteOpenHelper
import androidx.sqlite.db.SupportSQLiteStatement
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.deedeedev.ytreader.domain.SubtitleIdentity
import com.deedeedev.ytreader.domain.YouTubeVideoIdNormalizer
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class AppDatabaseMigrationTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private val testDbName = "migration-test.db"

    @After
    fun cleanup() {
        context.deleteDatabase(testDbName)
    }

    @Test
    fun migrate11To12_canonicalizesIdentityAndDeduplicates() = runBlocking {
        createVersion11DatabaseWithLegacyRows()

        val migration11To12 = object : Migration(11, 12) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS subtitles_new (
                        id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        videoId TEXT NOT NULL,
                        videoUrl TEXT NOT NULL,
                        title TEXT NOT NULL,
                        channelName TEXT NOT NULL,
                        languageCode TEXT NOT NULL,
                        subtitleTrackId TEXT,
                        isAutoGenerated INTEGER NOT NULL,
                        trackIdentity TEXT NOT NULL,
                        content TEXT NOT NULL,
                        studyContent TEXT,
                        lastTimestamp INTEGER NOT NULL,
                        lastOpenedAt INTEGER NOT NULL,
                        lastStudyScroll INTEGER NOT NULL,
                        fontSize REAL NOT NULL,
                        createdAt INTEGER NOT NULL,
                        uploadDate INTEGER NOT NULL,
                        fontFamily TEXT NOT NULL,
                        highlights TEXT NOT NULL,
                        aiCleaningInProgress INTEGER NOT NULL,
                        aiCleaningSourceText TEXT,
                        aiCleaningPendingResult TEXT,
                        aiCleaningErrorSummary TEXT,
                        aiCleaningErrorLog TEXT,
                        aiCleaningUpdatedAt INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                db.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS index_subtitles_new_videoId_trackIdentity ON subtitles_new(videoId, trackIdentity)"
                )

                val cursor = db.query(
                    """
                    SELECT id, videoId, title, channelName, languageCode, subtitleTrackId, isAutoGenerated,
                           content, studyContent, lastTimestamp, lastOpenedAt, lastStudyScroll, fontSize,
                           createdAt, uploadDate, fontFamily, highlights, aiCleaningInProgress,
                           aiCleaningSourceText, aiCleaningPendingResult, aiCleaningErrorSummary,
                           aiCleaningErrorLog, aiCleaningUpdatedAt
                    FROM subtitles
                    ORDER BY createdAt DESC, id DESC
                    """.trimIndent()
                )

                val statement = db.compileStatement(
                    """
                    INSERT OR IGNORE INTO subtitles_new (
                        id, videoId, videoUrl, title, channelName, languageCode, subtitleTrackId,
                        isAutoGenerated, trackIdentity, content, studyContent, lastTimestamp,
                        lastOpenedAt, lastStudyScroll, fontSize, createdAt, uploadDate, fontFamily,
                        highlights, aiCleaningInProgress, aiCleaningSourceText, aiCleaningPendingResult,
                        aiCleaningErrorSummary, aiCleaningErrorLog, aiCleaningUpdatedAt
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """.trimIndent()
                )

                cursor.use {
                    while (it.moveToNext()) {
                        val legacyVideoId = it.getString(it.getColumnIndexOrThrow("videoId"))
                        val languageCode = it.getString(it.getColumnIndexOrThrow("languageCode"))
                        val subtitleTrackId = it.getNullableString("subtitleTrackId")
                        val isAutoGenerated = it.getInt(it.getColumnIndexOrThrow("isAutoGenerated")) != 0
                        val canonicalVideoRef = YouTubeVideoIdNormalizer.canonicalize(legacyVideoId)
                        val trackIdentity = SubtitleIdentity.fromTrack(
                            subtitleTrackId = subtitleTrackId,
                            languageCode = languageCode,
                            isAutoGenerated = isAutoGenerated
                        )

                        statement.clearBindings()
                        statement.bindLong(1, it.getLong(it.getColumnIndexOrThrow("id")))
                        statement.bindString(2, canonicalVideoRef.videoId)
                        statement.bindString(3, canonicalVideoRef.videoUrl)
                        statement.bindString(4, it.getString(it.getColumnIndexOrThrow("title")))
                        statement.bindString(5, it.getString(it.getColumnIndexOrThrow("channelName")))
                        statement.bindString(6, languageCode)
                        if (subtitleTrackId == null) {
                            statement.bindNull(7)
                        } else {
                            statement.bindString(7, subtitleTrackId)
                        }
                        statement.bindLong(8, if (isAutoGenerated) 1L else 0L)
                        statement.bindString(9, trackIdentity)
                        statement.bindString(10, it.getString(it.getColumnIndexOrThrow("content")))
                        bindNullableString(statement, 11, it.getNullableString("studyContent"))
                        statement.bindLong(12, it.getLong(it.getColumnIndexOrThrow("lastTimestamp")))
                        statement.bindLong(13, it.getLong(it.getColumnIndexOrThrow("lastOpenedAt")))
                        statement.bindLong(14, it.getLong(it.getColumnIndexOrThrow("lastStudyScroll")))
                        statement.bindDouble(15, it.getDouble(it.getColumnIndexOrThrow("fontSize")))
                        statement.bindLong(16, it.getLong(it.getColumnIndexOrThrow("createdAt")))
                        statement.bindLong(17, it.getLong(it.getColumnIndexOrThrow("uploadDate")))
                        statement.bindString(18, it.getString(it.getColumnIndexOrThrow("fontFamily")))
                        statement.bindString(19, it.getString(it.getColumnIndexOrThrow("highlights")))
                        statement.bindLong(20, it.getLong(it.getColumnIndexOrThrow("aiCleaningInProgress")))
                        bindNullableString(statement, 21, it.getNullableString("aiCleaningSourceText"))
                        bindNullableString(statement, 22, it.getNullableString("aiCleaningPendingResult"))
                        bindNullableString(statement, 23, it.getNullableString("aiCleaningErrorSummary"))
                        bindNullableString(statement, 24, it.getNullableString("aiCleaningErrorLog"))
                        statement.bindLong(25, it.getLong(it.getColumnIndexOrThrow("aiCleaningUpdatedAt")))
                        statement.executeInsert()
                    }
                }

                db.execSQL("DROP TABLE subtitles")
                db.execSQL("ALTER TABLE subtitles_new RENAME TO subtitles")
                db.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS index_subtitles_videoId_trackIdentity ON subtitles(videoId, trackIdentity)"
                )
            }
        }

        val migratedDb = Room.databaseBuilder(context, AppDatabase::class.java, testDbName)
            .addMigrations(migration11To12)
            .build()

        val migrated = migratedDb.subtitleDao().getAll().first()
        assertEquals(3, migrated.size)

        val canonicalVideoId = "dQw4w9WgXcQ"
        val canonicalTrackIdentity = SubtitleIdentity.fromTrack(
            subtitleTrackId = "track-main",
            languageCode = "en",
            isAutoGenerated = false
        )
        val deduplicated = migrated.firstOrNull {
            it.videoId == canonicalVideoId && it.trackIdentity == canonicalTrackIdentity
        }
        assertNotNull(deduplicated)
        assertEquals("New content", deduplicated?.content)
        assertEquals(
            YouTubeVideoIdNormalizer.canonicalWatchUrl(canonicalVideoId),
            deduplicated?.videoUrl
        )

        val duplicateInsertResult = migratedDb.subtitleDao().insertIgnore(
            SubtitleEntity(
                videoId = canonicalVideoId,
                videoUrl = YouTubeVideoIdNormalizer.canonicalWatchUrl(canonicalVideoId),
                title = "Duplicate",
                channelName = "Uploader",
                languageCode = "en",
                subtitleTrackId = "track-main",
                trackIdentity = canonicalTrackIdentity,
                isAutoGenerated = false,
                content = "Should be ignored"
            )
        )
        assertEquals(-1L, duplicateInsertResult)

        val legacyUnparseable = migrated.firstOrNull { it.title == "Unparseable URL" }
        assertNotNull(legacyUnparseable)
        assertEquals("not a youtube url", legacyUnparseable?.videoId)
        assertEquals("not a youtube url", legacyUnparseable?.videoUrl)

        migratedDb.close()
    }

    private fun createVersion11DatabaseWithLegacyRows() {
        val callback = object : SupportSQLiteOpenHelper.Callback(11) {
            override fun onCreate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS subtitles (
                        id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        videoId TEXT NOT NULL,
                        title TEXT NOT NULL,
                        channelName TEXT NOT NULL,
                        languageCode TEXT NOT NULL,
                        subtitleTrackId TEXT,
                        isAutoGenerated INTEGER NOT NULL,
                        content TEXT NOT NULL,
                        studyContent TEXT,
                        lastTimestamp INTEGER NOT NULL,
                        lastOpenedAt INTEGER NOT NULL,
                        lastStudyScroll INTEGER NOT NULL,
                        fontSize REAL NOT NULL,
                        createdAt INTEGER NOT NULL,
                        uploadDate INTEGER NOT NULL,
                        fontFamily TEXT NOT NULL,
                        highlights TEXT NOT NULL,
                        aiCleaningInProgress INTEGER NOT NULL,
                        aiCleaningSourceText TEXT,
                        aiCleaningPendingResult TEXT,
                        aiCleaningErrorSummary TEXT,
                        aiCleaningErrorLog TEXT,
                        aiCleaningUpdatedAt INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                db.execSQL(
                    """
                    INSERT INTO subtitles (id, videoId, title, channelName, languageCode, subtitleTrackId,
                        isAutoGenerated, content, studyContent, lastTimestamp, lastOpenedAt, lastStudyScroll,
                        fontSize, createdAt, uploadDate, fontFamily, highlights, aiCleaningInProgress,
                        aiCleaningSourceText, aiCleaningPendingResult, aiCleaningErrorSummary, aiCleaningErrorLog,
                        aiCleaningUpdatedAt)
                    VALUES
                        (1, 'https://youtu.be/dQw4w9WgXcQ?t=1', 'Legacy variant old', 'Uploader', 'en', 'track-main',
                            0, 'Old content', NULL, 1000, 0, 0, 16.0, 100, 200, 'Default', '', 0,
                            NULL, NULL, NULL, NULL, 0),
                        (2, 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=abc', 'Legacy variant new', 'Uploader', 'en', 'track-main',
                            0, 'New content', NULL, 1000, 0, 0, 16.0, 200, 200, 'Default', '', 0,
                            NULL, NULL, NULL, NULL, 0),
                        (3, 'https://m.youtube.com/watch?v=dQw4w9WgXcQ', 'Auto fallback track', 'Uploader', 'it', NULL,
                            1, 'Auto content', NULL, 1000, 0, 0, 16.0, 150, 200, 'Default', '', 0,
                            NULL, NULL, NULL, NULL, 0),
                        (4, 'not a youtube url', 'Unparseable URL', 'Uploader', 'fr', NULL,
                            0, 'Legacy content', NULL, 1000, 0, 0, 16.0, 120, 200, 'Default', '', 0,
                            NULL, NULL, NULL, NULL, 0)
                    """.trimIndent()
                )
            }

            override fun onUpgrade(
                db: SupportSQLiteDatabase,
                oldVersion: Int,
                newVersion: Int
            ) {
            }
        }

        val configuration = SupportSQLiteOpenHelper.Configuration.builder(context)
            .name(testDbName)
            .callback(callback)
            .build()

        FrameworkSQLiteOpenHelperFactory()
            .create(configuration)
            .writableDatabase
            .close()
    }

    private fun Cursor.getNullableString(columnName: String): String? {
        val index = getColumnIndexOrThrow(columnName)
        return if (isNull(index)) null else getString(index)
    }

    private fun bindNullableString(statement: SupportSQLiteStatement, index: Int, value: String?) {
        if (value == null) {
            statement.bindNull(index)
        } else {
            statement.bindString(index, value)
        }
    }
}
