package com.deedeedev.ytreader.data.local

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class AppDatabaseMigrationTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private val testDbName = "migration-test.db"

    @After
    fun cleanup() {
        context.deleteDatabase(testDbName)
    }

    @Test
    fun latestSchema_isValidatedFromExportedJson() {
        val expectedIdentityHash = "e184049af610ab2f0e58988686c111eb"

        val database = Room.databaseBuilder(context, AppDatabase::class.java, testDbName).build()
        val runtimeIdentityHash = database.openHelper.writableDatabase
            .query("SELECT identity_hash FROM room_master_table WHERE id = 42")
            .use { cursor ->
                if (!cursor.moveToFirst()) {
                    null
                } else {
                    cursor.getString(cursor.getColumnIndexOrThrow("identity_hash"))
                }
            }

        assertNotNull(runtimeIdentityHash)
        assertEquals(expectedIdentityHash, runtimeIdentityHash)

        val indexNames = mutableListOf<String>()
        database.openHelper.writableDatabase.query("PRAGMA index_list(`subtitles`)").use { cursor ->
            val nameIndex = cursor.getColumnIndexOrThrow("name")
            while (cursor.moveToNext()) {
                indexNames.add(cursor.getString(nameIndex))
            }
        }

        assertTrue(indexNames.contains("index_subtitles_videoId_trackIdentity"))
        assertTrue(indexNames.contains("index_subtitles_createdAt"))
        assertTrue(indexNames.contains("index_subtitles_lastOpenedAt"))
        assertTrue(indexNames.contains("index_subtitles_isInLibrary"))
        assertTrue(indexNames.contains("index_subtitles_channelName"))

        val highlightNoteIndexNames = mutableListOf<String>()
        database.openHelper.writableDatabase.query("PRAGMA index_list(`highlight_notes`)").use { cursor ->
            val nameIndex = cursor.getColumnIndexOrThrow("name")
            while (cursor.moveToNext()) {
                highlightNoteIndexNames.add(cursor.getString(nameIndex))
            }
        }

        assertTrue(highlightNoteIndexNames.contains("index_highlight_notes_subtitleId"))
        assertTrue(
            highlightNoteIndexNames.contains(
                "index_highlight_notes_subtitleId_highlightStart_highlightEnd"
            )
        )
        database.close()
    }

    @Test
    fun insertIgnore_rejectsDuplicateVideoAndTrackIdentity() = runBlocking {
        val database = Room.databaseBuilder(context, AppDatabase::class.java, testDbName).build()

        val firstInsert = database.subtitleDao().insertIgnore(
            SubtitleEntity(
                videoId = "dQw4w9WgXcQ",
                videoUrl = "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                title = "First",
                channelName = "Uploader",
                languageCode = "en",
                subtitleTrackId = "track-main",
                trackIdentity = "track:track-main:manual",
                isAutoGenerated = false,
                content = "first-content"
            )
        )

        val duplicateInsert = database.subtitleDao().insertIgnore(
            SubtitleEntity(
                videoId = "dQw4w9WgXcQ",
                videoUrl = "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                title = "Duplicate",
                channelName = "Uploader",
                languageCode = "en",
                subtitleTrackId = "track-main",
                trackIdentity = "track:track-main:manual",
                isAutoGenerated = false,
                content = "duplicate-content"
            )
        )

        assertTrue(firstInsert > 0)
        assertEquals(-1L, duplicateInsert)

        database.close()
    }

    @Test
    fun entityDefaults_arePersistedOnInsert() = runBlocking {
        val database = Room.databaseBuilder(context, AppDatabase::class.java, testDbName).build()

        val id = database.subtitleDao().insertIgnore(
            SubtitleEntity(
                videoId = "dQw4w9WgXcQ",
                videoUrl = "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                title = "Defaults",
                channelName = "Uploader",
                languageCode = "en",
                content = "content"
            )
        )

        val stored = database.subtitleDao().getById(id)
        assertEquals(0L, stored?.lastOpenedAt)
        assertEquals(0, stored?.readingProgressPercent)
        assertEquals(0, stored?.lastStudyScroll)
        assertEquals(false, stored?.aiCleaningInProgress)
        assertEquals(0L, stored?.aiCleaningUpdatedAt)

        database.close()
    }
}
