package com.deedeedev.ytreader.data.local

import android.content.Context
import androidx.room.Room
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.sqlite.db.SupportSQLiteOpenHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class AppDatabaseMigrationTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private val testDbName = "migration-test.db"

    @After
    fun cleanup() {
        context.deleteDatabase(testDbName)
    }

    @Test
    fun migrate8To9_addsLastStudyScrollWithDefault() = runBlocking {
        createVersion8DatabaseWithSubtitleRow()

        val migration8To9 = object : Migration(8, 9) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    "ALTER TABLE subtitles ADD COLUMN lastStudyScroll INTEGER NOT NULL DEFAULT 0"
                )
            }
        }

        val migratedDb = Room.databaseBuilder(context, AppDatabase::class.java, testDbName)
            .addMigrations(migration8To9)
            .build()

        val migrated = migratedDb.subtitleDao().getAll().first().first()
        assertEquals(1L, migrated.id)
        assertEquals("video-1", migrated.videoId)
        assertEquals(42_000L, migrated.lastTimestamp)
        assertEquals(0, migrated.lastStudyScroll)

        migratedDb.close()
    }

    private fun createVersion8DatabaseWithSubtitleRow() {
        val callback = object : SupportSQLiteOpenHelper.Callback(8) {
            override fun onCreate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS subtitles (
                        id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        videoId TEXT NOT NULL,
                        title TEXT NOT NULL,
                        channelName TEXT NOT NULL,
                        languageCode TEXT NOT NULL,
                        subtitleTrackId TEXT,
                        isAutoGenerated INTEGER NOT NULL,
                        content TEXT NOT NULL,
                        studyContent TEXT,
                        lastTimestamp INTEGER NOT NULL,
                        fontSize REAL NOT NULL,
                        createdAt INTEGER NOT NULL,
                        uploadDate INTEGER NOT NULL,
                        fontFamily TEXT NOT NULL,
                        highlights TEXT NOT NULL
                    )
                    """.trimIndent()
                )
                db.execSQL(
                    """
                    INSERT INTO subtitles (
                        id,
                        videoId,
                        title,
                        channelName,
                        languageCode,
                        subtitleTrackId,
                        isAutoGenerated,
                        content,
                        studyContent,
                        lastTimestamp,
                        fontSize,
                        createdAt,
                        uploadDate,
                        fontFamily,
                        highlights
                    ) VALUES (
                        1,
                        'video-1',
                        'Title',
                        'Channel',
                        'en',
                        'track-1',
                        0,
                        'Original',
                        'Study',
                        42000,
                        18.0,
                        123456,
                        654321,
                        'Default',
                        ''
                    )
                    """.trimIndent()
                )
            }

            override fun onUpgrade(
                db: SupportSQLiteDatabase,
                oldVersion: Int,
                newVersion: Int
            ) {
            }
        }

        val configuration = SupportSQLiteOpenHelper.Configuration.builder(context)
            .name(testDbName)
            .callback(callback)
            .build()

        FrameworkSQLiteOpenHelperFactory()
            .create(configuration)
            .writableDatabase
            .close()
    }
}
