package com.deedeedev.ytreader.data.local

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.io.IOException

@RunWith(AndroidJUnit4::class)
class SubtitleDaoTest {
    private lateinit var subtitleDao: SubtitleDao
    private lateinit var db: AppDatabase

    @Before
    fun createDb() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        db = Room.inMemoryDatabaseBuilder(
            context, AppDatabase::class.java
        ).build()
        subtitleDao = db.subtitleDao()
    }

    @After
    @Throws(IOException::class)
    fun closeDb() {
        db.close()
    }

    @Test
    @Throws(Exception::class)
    fun insertAndGetSubtitle() = runBlocking {
        val subtitle = SubtitleEntity(
            videoId = "123",
            title = "Test Video",
            languageCode = "en",
            content = "Hello World"
        )
        subtitleDao.upsertByIdentity(subtitle)
        
        val allSubtitles = subtitleDao.getAll().first()
        assertEquals(1, allSubtitles.size)
        assertEquals("Test Video", allSubtitles[0].title)
        
        // Check getById
        val insertedId = allSubtitles[0].id
        val fetched = subtitleDao.getById(insertedId)
        assertEquals("Hello World", fetched?.content)
    }

    @Test
    @Throws(Exception::class)
    fun updateHighlights_persistsValue() = runBlocking {
        val subtitle = SubtitleEntity(
            videoId = "highlight-123",
            title = "Highlight Test",
            languageCode = "en",
            content = "Hello World"
        )
        subtitleDao.upsertByIdentity(subtitle)

        val inserted = subtitleDao.getAll().first().first()
        val highlights = "0,5,RED|6,11,BLUE"
        subtitleDao.updateHighlights(inserted.id, highlights)

        val fetched = subtitleDao.getById(inserted.id)
        assertEquals(highlights, fetched?.highlights)
    }

    @Test
    @Throws(Exception::class)
    fun insertSameLanguageManualAndAuto_persistsBothRows() = runBlocking {
        val manual = SubtitleEntity(
            videoId = "video-123",
            title = "Test Video",
            languageCode = "it",
            subtitleTrackId = "track-manual",
            isAutoGenerated = false,
            content = "manual content"
        )
        val auto = SubtitleEntity(
            videoId = "video-123",
            title = "Test Video",
            languageCode = "it",
            subtitleTrackId = "track-auto",
            isAutoGenerated = true,
            content = "auto content"
        )

        subtitleDao.upsertByIdentity(manual)
        subtitleDao.upsertByIdentity(auto)

        val saved = subtitleDao.getAll().first().filter { it.videoId == "video-123" && it.languageCode == "it" }
        assertEquals(2, saved.size)
    }

    @Test
    @Throws(Exception::class)
    fun replaceContentForRedownload_resetsDerivedReaderState() = runBlocking {
        val subtitle = SubtitleEntity(
            videoId = "redownload-123",
            title = "Redownload Test",
            languageCode = "en",
            content = "old raw content",
            studyContent = "edited study content",
            readingProgressPercent = 84,
            lastTimestamp = 42L,
            lastStudyScroll = 7,
            highlights = "0,4,YELLOW"
        )
        subtitleDao.upsertByIdentity(subtitle)

        val inserted = subtitleDao.getAll().first().first()
        val newCreatedAt = inserted.createdAt + 1_000L

        subtitleDao.replaceContentForRedownload(
            id = inserted.id,
            content = "new raw content",
            createdAt = newCreatedAt
        )

        val fetched = subtitleDao.getById(inserted.id)
        assertEquals("new raw content", fetched?.content)
        assertEquals(newCreatedAt, fetched?.createdAt)
        assertEquals(null, fetched?.studyContent)
        assertEquals("", fetched?.highlights)
        assertEquals(0L, fetched?.lastTimestamp)
        assertEquals(0, fetched?.lastStudyScroll)
        assertEquals(0, fetched?.readingProgressPercent)
    }

    @Test
    @Throws(Exception::class)
    fun cancelAiCleaning_clearsTransientAiCleaningState() = runBlocking {
        val subtitle = SubtitleEntity(
            videoId = "ai-cleaning-123",
            title = "AI Cleaning Test",
            languageCode = "en",
            content = "raw content"
        )
        subtitleDao.upsertByIdentity(subtitle)

        val inserted = subtitleDao.getAll().first().first()
        subtitleDao.markAiCleaningQueued(
            id = inserted.id,
            sourceText = "source text",
            updatedAt = 100L
        )
        subtitleDao.storeAiCleaningFailure(
            id = inserted.id,
            summary = "Old error",
            log = "Old log",
            updatedAt = 150L
        )
        subtitleDao.markAiCleaningQueued(
            id = inserted.id,
            sourceText = "source text",
            updatedAt = 200L
        )

        subtitleDao.cancelAiCleaning(
            id = inserted.id,
            updatedAt = 300L
        )

        val fetched = subtitleDao.getById(inserted.id)
        assertNotNull(fetched)
        assertFalse(fetched!!.aiCleaningInProgress)
        assertNull(fetched.aiCleaningSourceText)
        assertNull(fetched.aiCleaningPendingResult)
        assertNull(fetched.aiCleaningErrorSummary)
        assertNull(fetched.aiCleaningErrorLog)
        assertEquals(300L, fetched.aiCleaningUpdatedAt)
    }

    @Test
    @Throws(Exception::class)
    fun observeLibraryVideoRows_groupsByVideoAndSortsByDownloaded() = runBlocking {
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-a",
                title = "Alpha Old",
                channelName = "Channel A",
                languageCode = "en",
                subtitleTrackId = "track-a-en",
                content = "content",
                createdAt = 100L,
                lastOpenedAt = 10L,
                readingProgressPercent = 35,
                uploadDate = 1_000L
            )
        )
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-a",
                title = "Alpha New",
                channelName = "Channel A",
                languageCode = "it",
                subtitleTrackId = "track-a-it",
                content = "content",
                createdAt = 200L,
                lastOpenedAt = 50L,
                readingProgressPercent = 100,
                uploadDate = 1_000L
            )
        )
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-b",
                title = "Beta",
                channelName = "Channel B",
                languageCode = "en",
                subtitleTrackId = "track-b-en",
                content = "content",
                createdAt = 300L,
                lastOpenedAt = 20L,
                readingProgressPercent = 10,
                uploadDate = 2_000L
            )
        )

        val rows = subtitleDao.observeLibraryVideoRows(
            channelName = null,
            sortOption = "DOWNLOADED",
            isAscending = false
        ).first()

        assertEquals(2, rows.size)
        assertEquals("video-b", rows[0].videoId)
        assertEquals("video-a", rows[1].videoId)
        assertEquals("Alpha New", rows[1].title)
        assertEquals(200L, rows[1].lastDownloaded)
        assertEquals(50L, rows[1].lastOpenedAt)
        assertEquals(100, rows[1].readingProgressPercent)
    }

    @Test
    @Throws(Exception::class)
    fun updateReadingProgressPercent_keepsMaximumValue() = runBlocking {
        val subtitle = SubtitleEntity(
            videoId = "progress-123",
            title = "Progress Test",
            languageCode = "en",
            content = "content"
        )
        subtitleDao.upsertByIdentity(subtitle)

        val inserted = subtitleDao.getAll().first().first()

        subtitleDao.updateReadingProgressPercent(inserted.id, 45)
        subtitleDao.updateReadingProgressPercent(inserted.id, 30)
        subtitleDao.updateReadingProgressPercent(inserted.id, 100)

        val fetched = subtitleDao.getById(inserted.id)
        assertEquals(100, fetched?.readingProgressPercent)
    }

    @Test
    @Throws(Exception::class)
    fun resetReadingProgressForVideo_resetsAllTracksAndAggregates() = runBlocking {
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-reset",
                title = "Reset Me",
                channelName = "Channel A",
                languageCode = "en",
                subtitleTrackId = "track-en",
                content = "content",
                lastTimestamp = 42L,
                lastStudyScroll = 5,
                readingProgressPercent = 35,
                createdAt = 100L
            )
        )
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-reset",
                title = "Reset Me",
                channelName = "Channel A",
                languageCode = "it",
                subtitleTrackId = "track-it",
                content = "content",
                lastTimestamp = 99L,
                lastStudyScroll = 12,
                readingProgressPercent = 100,
                createdAt = 200L
            )
        )

        subtitleDao.resetReadingProgressForVideo("video-reset")

        val savedTracks = subtitleDao.getAll().first().filter { it.videoId == "video-reset" }
        assertEquals(2, savedTracks.size)
        assertTrue(savedTracks.all { it.readingProgressPercent == 0 })
        assertTrue(savedTracks.all { it.lastTimestamp == 0L })
        assertTrue(savedTracks.all { it.lastStudyScroll == 0 })

        val libraryRows = subtitleDao.observeLibraryVideoRows(
            channelName = null,
            sortOption = "DOWNLOADED",
            isAscending = false
        ).first()
        val libraryRow = libraryRows.first { it.videoId == "video-reset" }
        assertEquals(0, libraryRow.readingProgressPercent)

        val collectionRows = subtitleDao.observeCollectionVideoRows(
            videoIds = listOf("video-reset"),
            channelName = null,
            sortOption = "DOWNLOADED",
            isAscending = false
        ).first()
        assertEquals(1, collectionRows.size)
        assertEquals(0, collectionRows[0].readingProgressPercent)
    }

    @Test
    @Throws(Exception::class)
    fun markVideoAsRead_setsAllTracksToHundredWithoutChangingPosition() = runBlocking {
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-read",
                title = "Read Me",
                channelName = "Channel B",
                languageCode = "en",
                subtitleTrackId = "track-en",
                content = "content",
                lastTimestamp = 42L,
                lastStudyScroll = 5,
                readingProgressPercent = 35,
                createdAt = 100L
            )
        )
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-read",
                title = "Read Me",
                channelName = "Channel B",
                languageCode = "it",
                subtitleTrackId = "track-it",
                content = "content",
                lastTimestamp = 99L,
                lastStudyScroll = 12,
                readingProgressPercent = 0,
                createdAt = 200L
            )
        )

        subtitleDao.markVideoAsRead("video-read")

        val savedTracks = subtitleDao.getAll().first().filter { it.videoId == "video-read" }
        assertEquals(2, savedTracks.size)
        assertTrue(savedTracks.all { it.readingProgressPercent == 100 })
        assertEquals(listOf(42L, 99L), savedTracks.map { it.lastTimestamp }.sorted())
        assertEquals(listOf(5, 12), savedTracks.map { it.lastStudyScroll }.sorted())

        val libraryRows = subtitleDao.observeLibraryVideoRows(
            channelName = null,
            sortOption = "DOWNLOADED",
            isAscending = false
        ).first()
        val libraryRow = libraryRows.first { it.videoId == "video-read" }
        assertEquals(100, libraryRow.readingProgressPercent)

        val collectionRows = subtitleDao.observeCollectionVideoRows(
            videoIds = listOf("video-read"),
            channelName = null,
            sortOption = "DOWNLOADED",
            isAscending = false
        ).first()
        assertEquals(1, collectionRows.size)
        assertEquals(100, collectionRows[0].readingProgressPercent)
    }

    @Test
    @Throws(Exception::class)
    fun observeLibraryVideoRows_appliesChannelFilter() = runBlocking {
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-a",
                title = "Alpha",
                channelName = "One",
                languageCode = "en",
                subtitleTrackId = "track-a-en",
                content = "content"
            )
        )
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-b",
                title = "Beta",
                channelName = "Two",
                languageCode = "en",
                subtitleTrackId = "track-b-en",
                content = "content"
            )
        )

        val filtered = subtitleDao.observeLibraryVideoRows(
            channelName = "One",
            sortOption = "TITLE",
            isAscending = true
        ).first()

        assertEquals(1, filtered.size)
        assertEquals("video-a", filtered[0].videoId)
        assertEquals("One", filtered[0].channelName)
    }

    @Test
    @Throws(Exception::class)
    fun collectionQueries_ignoreMissingVideoIdsAndReturnTracks() = runBlocking {
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-a",
                title = "Gamma",
                channelName = "Channel A",
                languageCode = "it",
                subtitleTrackId = "track-a-it",
                content = "content",
                createdAt = 200L
            )
        )
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-a",
                title = "Gamma",
                channelName = "Channel A",
                languageCode = "en",
                subtitleTrackId = "track-a-en",
                content = "content",
                createdAt = 201L
            )
        )
        subtitleDao.upsertByIdentity(
            SubtitleEntity(
                videoId = "video-b",
                title = "Delta",
                channelName = "Channel B",
                languageCode = "fr",
                subtitleTrackId = "track-b-fr",
                content = "content",
                createdAt = 300L
            )
        )

        val collectionIds = listOf("video-a", "missing", "video-b")
        val rows = subtitleDao.observeCollectionVideoRows(
            videoIds = collectionIds,
            channelName = null,
            sortOption = "TITLE",
            isAscending = true
        ).first()
        val count = subtitleDao.observeCollectionVideoCount(collectionIds).first()
        val tracks = subtitleDao.observeSubtitleTracksForVideos(listOf("video-a")).first()

        assertEquals(2, rows.size)
        assertEquals(2, count)
        assertTrue(rows.none { it.videoId == "missing" })
        assertEquals(listOf("en", "it"), tracks.map { it.languageCode })
    }
}
