package com.deedeedev.ytreader.domain

import com.deedeedev.ytreader.data.local.SubtitleEntity
import org.schabi.newpipe.extractor.stream.SubtitlesStream

object SubtitleIdentity {
    private const val TRACK_PREFIX = "track"
    private const val LANGUAGE_PREFIX = "lang"

    fun fromTrack(
        subtitleTrackId: String?,
        languageCode: String?,
        isAutoGenerated: Boolean
    ): String {
        val normalizedTrackId = subtitleTrackId?.trim().orEmpty()
        val normalizedLanguageCode = languageCode?.trim().orEmpty().ifBlank { "unknown" }.lowercase()
        val autoFlag = if (isAutoGenerated) "auto" else "manual"
        return if (normalizedTrackId.isNotBlank()) {
            "$TRACK_PREFIX:$normalizedTrackId:$autoFlag"
        } else {
            "$LANGUAGE_PREFIX:$normalizedLanguageCode:$autoFlag"
        }
    }

    fun fromEntity(entity: SubtitleEntity): String {
        return entity.trackIdentity.ifBlank {
            fromTrack(entity.subtitleTrackId, entity.languageCode, entity.isAutoGenerated)
        }
    }

    fun fromStream(stream: SubtitlesStream): String {
        return fromTrack(stream.id, stream.languageTag, stream.isAutoGenerated)
    }
}
