package com.deedeedev.ytreader.ui.home

import com.deedeedev.ytreader.data.local.SubtitleEntity
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.schabi.newpipe.extractor.stream.SubtitlesStream

class SubtitleIdentityMatcherTest {

    private val videoId = "dQw4w9WgXcQ"
    private val canonicalUrl = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

    @Test
    fun matchesSavedSubtitle_doesNotMatchAutoForManual() {
        val savedManual = SubtitleEntity(
            videoId = videoId,
            videoUrl = canonicalUrl,
            title = "Video",
            languageCode = "it",
            isAutoGenerated = false,
            content = "manual"
        )
        val autoStream = buildSubtitlesStream(
            id = "track-auto",
            languageTag = "it",
            isAutoGenerated = true
        )

        val matches = SubtitleIdentityMatcher.matchesSavedSubtitle(
            savedSubtitle = savedManual,
            videoReference = "https://youtu.be/dQw4w9WgXcQ?t=1",
            stream = autoStream
        )

        assertFalse(matches)
    }

    @Test
    fun matchesSavedSubtitle_doesNotMatchManualForAuto() {
        val savedAuto = SubtitleEntity(
            videoId = videoId,
            videoUrl = canonicalUrl,
            title = "Video",
            languageCode = "it",
            isAutoGenerated = true,
            content = "auto"
        )
        val manualStream = buildSubtitlesStream(
            id = "track-manual",
            languageTag = "it",
            isAutoGenerated = false
        )

        val matches = SubtitleIdentityMatcher.matchesSavedSubtitle(
            savedSubtitle = savedAuto,
            videoReference = canonicalUrl,
            stream = manualStream
        )

        assertFalse(matches)
    }

    @Test
    fun findMatchingStream_usesTrackIdWhenAvailable() {
        val savedAuto = SubtitleEntity(
            videoId = videoId,
            videoUrl = canonicalUrl,
            title = "Video",
            languageCode = "it",
            subtitleTrackId = "track-auto",
            trackIdentity = "track:track-auto:auto",
            isAutoGenerated = true,
            content = "auto"
        )
        val manualStream = buildSubtitlesStream(
            id = "track-manual",
            languageTag = "it",
            isAutoGenerated = false
        )
        val autoStream = buildSubtitlesStream(
            id = "track-auto",
            languageTag = "it",
            isAutoGenerated = true
        )

        val match = SubtitleIdentityMatcher.findMatchingStream(
            savedSubtitle = savedAuto,
            streams = listOf(manualStream, autoStream)
        )

        assertNotNull(match)
        assertTrue(match?.isAutoGenerated == true)
    }

    @Test
    fun findMatchingStream_fallsBackToLanguageAndAutoGenerated() {
        val legacyManual = SubtitleEntity(
            videoId = videoId,
            videoUrl = canonicalUrl,
            title = "Video",
            languageCode = "it",
            subtitleTrackId = null,
            isAutoGenerated = false,
            content = "manual"
        )
        val autoStream = buildSubtitlesStream(
            id = "track-auto",
            languageTag = "it",
            isAutoGenerated = true
        )

        val match = SubtitleIdentityMatcher.findMatchingStream(
            savedSubtitle = legacyManual,
            streams = listOf(autoStream)
        )

        assertNull(match)
    }

    private fun buildSubtitlesStream(
        id: String,
        languageTag: String,
        isAutoGenerated: Boolean
    ): SubtitlesStream {
        return SubtitlesStream.Builder()
            .setId(id)
            .setContent("https://example.com/subtitle", true)
            .setLanguageCode(languageTag)
            .setAutoGenerated(isAutoGenerated)
            .build()
    }
}
