package com.deedeedev.ytreader.ui.home

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import org.schabi.newpipe.extractor.stream.SubtitlesStream

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Clear
import androidx.compose.material.icons.filled.Download
import androidx.compose.material.icons.automirrored.filled.MenuBook

@Composable
fun SearchScreen(
    viewModel: HomeViewModel,
    onSubtitleClick: (Long) -> Unit,
    modifier: Modifier = Modifier
) {
    val uiState by viewModel.uiState.collectAsState()

    Column(
        modifier = modifier
            .fillMaxSize()
            .padding(16.dp)
    ) {
        // Search Area
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically
        ) {
            OutlinedTextField(
                value = uiState.url,
                onValueChange = viewModel::onUrlChange,
                label = { Text("YouTube URL") },
                modifier = Modifier.weight(1f),
                singleLine = true,
                trailingIcon = {
                    if (uiState.url.isNotEmpty()) {
                        IconButton(onClick = { viewModel.onUrlChange("") }) {
                            Icon(
                                imageVector = Icons.Default.Clear,
                                contentDescription = "Clear search"
                            )
                        }
                    }
                }
            )
            Spacer(modifier = Modifier.width(8.dp))
            Button(onClick = viewModel::searchVideo, enabled = !uiState.isLoading) {
                Text("Search")
            }
        }

        if (uiState.isLoading) {
            LinearProgressIndicator(modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp))
        }

        if (uiState.error != null) {
            Text(
                text = uiState.error!!,
                color = MaterialTheme.colorScheme.error,
                modifier = Modifier.padding(vertical = 8.dp)
            )
        }

        // Available Subtitles
        uiState.streamInfo?.let { info ->
            Text(
                text = info.name,
                style = MaterialTheme.typography.titleMedium,
                modifier = Modifier.padding(vertical = 8.dp)
            )
            
            Text(
                text = "Available Subtitles",
                style = MaterialTheme.typography.labelLarge
            )

            LazyColumn(modifier = Modifier.weight(1f)) {
                val subtitles: List<SubtitlesStream> = try {
                        (info.subtitles ?: emptyList()).sortedBy { it.languageTag }
                } catch (e: Exception) {
                    emptyList()
                }
                
                items(subtitles) { subtitle ->
                    val savedSubtitle = uiState.savedSubtitles.find { 
                        it.videoId == info.url && it.languageCode == subtitle.languageTag 
                    }
                    
                    SubtitleItem(
                        subtitle = subtitle,
                        isDownloaded = savedSubtitle != null,
                        onDownload = { viewModel.downloadSubtitle(subtitle) },
                        onView = { savedSubtitle?.let { onSubtitleClick(it.id) } }
                    )
                }
            }
        }
    }
}

@Composable
fun SubtitleItem(
    subtitle: SubtitlesStream,
    isDownloaded: Boolean,
    onDownload: () -> Unit,
    onView: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 4.dp),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically
    ) {
        Column {
            val languageCode = subtitle.languageTag ?: "Unknown"
            val displayName = subtitle.displayLanguageName
            val text = if (!displayName.isNullOrBlank() && displayName != languageCode) {
                "$languageCode - $displayName"
            } else {
                languageCode
            }
            Text(text = text)
            if (subtitle.isAutoGenerated) {
                Text(text = "Auto-generated", style = MaterialTheme.typography.bodySmall)
            }
        }
        if (isDownloaded) {
            IconButton(onClick = onView) {
                Icon(
                    imageVector = Icons.AutoMirrored.Filled.MenuBook,
                    contentDescription = "Read Subtitle"
                )
            }
        } else {
            IconButton(onClick = onDownload) {
                Icon(
                    imageVector = Icons.Default.Download,
                    contentDescription = "Download Subtitle"
                )
            }
        }
    }
}
