package com.deedeedev.ytreader.ui.home

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import org.schabi.newpipe.extractor.stream.SubtitlesStream

@Composable
fun SearchScreen(
    viewModel: HomeViewModel,
    modifier: Modifier = Modifier
) {
    val uiState by viewModel.uiState.collectAsState()

    Column(
        modifier = modifier
            .fillMaxSize()
            .padding(16.dp)
    ) {
        // Search Area
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically
        ) {
            OutlinedTextField(
                value = uiState.url,
                onValueChange = viewModel::onUrlChange,
                label = { Text("YouTube URL") },
                modifier = Modifier.weight(1f),
                singleLine = true
            )
            Spacer(modifier = Modifier.width(8.dp))
            Button(onClick = viewModel::searchVideo, enabled = !uiState.isLoading) {
                Text("Search")
            }
        }

        if (uiState.isLoading) {
            LinearProgressIndicator(modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp))
        }

        if (uiState.error != null) {
            Text(
                text = uiState.error!!,
                color = MaterialTheme.colorScheme.error,
                modifier = Modifier.padding(vertical = 8.dp)
            )
        }

        // Available Subtitles
        uiState.streamInfo?.let { info ->
            Text(
                text = info.name,
                style = MaterialTheme.typography.titleMedium,
                modifier = Modifier.padding(vertical = 8.dp)
            )
            
            Text(
                text = "Available Subtitles",
                style = MaterialTheme.typography.labelLarge
            )

            LazyColumn(modifier = Modifier.weight(1f)) {
                val subtitles: List<SubtitlesStream> = try {
                        info.subtitles ?: emptyList()
                } catch (e: Exception) {
                    emptyList()
                }
                
                items(subtitles) { subtitle ->
                    SubtitleItem(subtitle = subtitle) {
                        viewModel.downloadSubtitle(subtitle)
                    }
                }
            }
        }
    }
}

@Composable
fun SubtitleItem(
    subtitle: SubtitlesStream,
    onDownload: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 4.dp),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically
    ) {
        Column {
            Text(text = subtitle.languageTag ?: "Unknown Language")
            if (subtitle.isAutoGenerated) {
                Text(text = "Auto-generated", style = MaterialTheme.typography.bodySmall)
            }
        }
        Button(onClick = onDownload) {
            Text("Download")
        }
    }
}
