package com.deedeedev.ytreader.ui.home

import com.deedeedev.ytreader.data.local.SubtitleEntity
import org.schabi.newpipe.extractor.stream.SubtitlesStream

object SubtitleIdentityMatcher {
    fun matchesSavedSubtitle(
        savedSubtitle: SubtitleEntity,
        videoId: String,
        stream: SubtitlesStream
    ): Boolean {
        if (savedSubtitle.videoId != videoId) {
            return false
        }
        return matchesSavedTrack(savedSubtitle, stream)
    }

    fun findMatchingStream(
        savedSubtitle: SubtitleEntity,
        streams: List<SubtitlesStream>?
    ): SubtitlesStream? {
        if (streams.isNullOrEmpty()) {
            return null
        }
        return streams.firstOrNull { stream -> matchesSavedTrack(savedSubtitle, stream) }
    }

    private fun matchesSavedTrack(savedSubtitle: SubtitleEntity, stream: SubtitlesStream): Boolean {
        val savedTrackId = savedSubtitle.subtitleTrackId?.takeIf { it.isNotBlank() }
        if (savedTrackId != null) {
            return savedTrackId == stream.id && savedSubtitle.isAutoGenerated == stream.isAutoGenerated
        }
        val streamLanguage = stream.languageTag ?: return false
        return savedSubtitle.languageCode.equals(streamLanguage, ignoreCase = true)
            && savedSubtitle.isAutoGenerated == stream.isAutoGenerated
    }
}
