package com.deedeedev.ytreader.ui.home

import com.deedeedev.ytreader.data.local.SubtitleEntity
import com.deedeedev.ytreader.domain.SubtitleIdentity
import com.deedeedev.ytreader.domain.YouTubeVideoIdNormalizer
import org.schabi.newpipe.extractor.stream.SubtitlesStream

object SubtitleIdentityMatcher {
    fun matchesSavedSubtitle(
        savedSubtitle: SubtitleEntity,
        videoReference: String?,
        stream: SubtitlesStream
    ): Boolean {
        val candidateVideoId = YouTubeVideoIdNormalizer.extractVideoId(videoReference)
            ?: videoReference?.trim().orEmpty()
        if (savedSubtitle.videoId != candidateVideoId) {
            return false
        }
        return matchesSavedTrack(savedSubtitle, stream)
    }

    fun findMatchingStream(
        savedSubtitle: SubtitleEntity,
        streams: List<SubtitlesStream>?
    ): SubtitlesStream? {
        if (streams.isNullOrEmpty()) {
            return null
        }
        return streams.firstOrNull { stream -> matchesSavedTrack(savedSubtitle, stream) }
    }

    private fun matchesSavedTrack(savedSubtitle: SubtitleEntity, stream: SubtitlesStream): Boolean {
        val streamTrackIdentity = SubtitleIdentity.fromStream(stream)
        val savedTrackIdentity = SubtitleIdentity.fromEntity(savedSubtitle)
        if (savedTrackIdentity.isNotBlank()) {
            return savedTrackIdentity == streamTrackIdentity
        }

        val savedTrackId = savedSubtitle.subtitleTrackId?.takeIf { it.isNotBlank() }
        if (savedTrackId != null) {
            return savedTrackId == stream.id && savedSubtitle.isAutoGenerated == stream.isAutoGenerated
        }

        val streamLanguage = stream.languageTag ?: return false
        return savedSubtitle.languageCode.equals(streamLanguage, ignoreCase = true)
            && savedSubtitle.isAutoGenerated == stream.isAutoGenerated
    }
}
