package com.deedeedev.ytreader.data

import android.content.ClipData
import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.deedeedev.ytreader.R
import com.deedeedev.ytreader.data.local.BookmarkDao
import com.deedeedev.ytreader.data.local.BookmarkEntity
import com.deedeedev.ytreader.data.local.HighlightNoteDao
import com.deedeedev.ytreader.data.local.SubtitleDao
import com.deedeedev.ytreader.data.local.VideoDao
import com.deedeedev.ytreader.domain.SubtitleParser
import com.deedeedev.ytreader.ui.reader.TextHighlight
import com.deedeedev.ytreader.ui.reader.parseHighlights
import kotlinx.coroutines.flow.first
import java.io.BufferedOutputStream
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID
import java.util.zip.CRC32
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

enum class EpubExportMode {
    CLEAN,
    ANNOTATED
}

suspend fun exportEpub(
    context: Context,
    subtitleDao: SubtitleDao,
    videoDao: VideoDao,
    highlightNoteDao: HighlightNoteDao,
    bookmarkDao: BookmarkDao,
    videoIds: List<String>,
    mode: EpubExportMode,
    bookTitle: String
): File {
    val subtitles = subtitleDao.observeSubtitleTracksForVideos(videoIds).first()
    val subtitleIds = subtitles.map { it.id }
    val highlightsBySubtitle = if (mode == EpubExportMode.ANNOTATED) {
        highlightNoteDao.observeBySubtitleIds(subtitleIds).first().groupBy { it.subtitleId }
    } else {
        emptyMap()
    }
    val bookmarksBySubtitle = if (mode == EpubExportMode.ANNOTATED) {
        bookmarkDao.observeBySubtitleIds(subtitleIds).first().groupBy { it.subtitleId }
    } else {
        emptyMap()
    }
    val videosByVideoId = videoIds.mapNotNull { id ->
        videoDao.getByVideoId(id)?.let { id to it }
    }.toMap()

    val subtitlesByVideo = subtitles.groupBy { it.videoId }

    val chapters = videoIds.mapNotNull { videoId ->
        val tracks = subtitlesByVideo[videoId] ?: return@mapNotNull null
        val video = videosByVideoId[videoId]
        val videoTitle = video?.title ?: tracks.firstOrNull()?.title ?: videoId
        EpubVideoChapter(
            videoId = videoId,
            title = videoTitle,
            channelName = video?.channelName ?: tracks.firstOrNull()?.channelName ?: "",
            videoUrl = video?.videoUrl ?: tracks.firstOrNull()?.videoUrl ?: "",
            uploadDate = video?.uploadDate ?: tracks.firstOrNull()?.uploadDate ?: 0L,
            tracks = tracks.map { track ->
                val text = track.aiCleaningPendingResult
                    ?: track.studyContent
                    ?: SubtitleParser.parse(track.content)
                val parsedHighlights = if (mode == EpubExportMode.ANNOTATED) {
                    parseHighlights(track.highlights)
                } else {
                    emptyList()
                }
                EpubTrackChapter(
                    subtitleId = track.id,
                    languageCode = track.languageCode,
                    isAutoGenerated = track.isAutoGenerated,
                    text = text,
                    highlights = parsedHighlights,
                    notes = highlightsBySubtitle[track.id].orEmpty(),
                    bookmarks = bookmarksBySubtitle[track.id].orEmpty()
                )
            }
        )
    }

    val exportDir = File(context.cacheDir, "exports").apply { mkdirs() }
    val fileName = sanitizeEpubFileName(bookTitle) + ".epub"
    val outputFile = File(exportDir, fileName)
    writeEpub(outputFile, bookTitle, chapters, mode)
    return outputFile
}

fun shareEpub(context: Context, file: File) {
    val uri = FileProvider.getUriForFile(
        context,
        "${context.packageName}.fileprovider",
        file
    )
    val shareIntent = Intent(Intent.ACTION_SEND).apply {
        type = "application/epub+zip"
        putExtra(Intent.EXTRA_STREAM, uri)
        clipData = ClipData.newRawUri(file.name, uri)
        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
    }
    context.startActivity(
        Intent.createChooser(shareIntent, context.getString(R.string.epub_export_title))
    )
}

private data class EpubVideoChapter(
    val videoId: String,
    val title: String,
    val channelName: String,
    val videoUrl: String,
    val uploadDate: Long,
    val tracks: List<EpubTrackChapter>
)

private data class EpubTrackChapter(
    val subtitleId: Long,
    val languageCode: String,
    val isAutoGenerated: Boolean,
    val text: String,
    val highlights: List<TextHighlight>,
    val notes: List<com.deedeedev.ytreader.data.local.HighlightNoteEntity>,
    val bookmarks: List<BookmarkEntity>
)

private fun writeEpub(
    outputFile: File,
    bookTitle: String,
    chapters: List<EpubVideoChapter>,
    mode: EpubExportMode
) {
    val uuid = UUID.randomUUID().toString()
    val timestamp = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US).apply {
        timeZone = java.util.TimeZone.getTimeZone("UTC")
    }.format(Date())

    ZipOutputStream(BufferedOutputStream(FileOutputStream(outputFile))).use { zip ->
        writeMimetype(zip)
        writeEntry(zip, "META-INF/container.xml", epubContainerXml())
        writeEntry(zip, "OEBPS/content.opf", epubContentOpf(bookTitle, uuid, timestamp, chapters))
        writeEntry(zip, "OEBPS/toc.ncx", epubTocNcx(bookTitle, uuid, chapters))
        writeEntry(zip, "OEBPS/Style/style.css", epubCss())

        chapters.forEachIndexed { videoIndex, chapter ->
            chapter.tracks.forEachIndexed { trackIndex, track ->
                val fileName = "chapter_${videoIndex}_${trackIndex}.xhtml"
                writeEntry(zip, "OEBPS/Text/$fileName", epubChapterXhtml(chapter, track, mode))
            }
        }
    }
}

private fun writeMimetype(zip: ZipOutputStream) {
    val bytes = "application/epub+zip".toByteArray(Charsets.US_ASCII)
    val crc = CRC32()
    crc.update(bytes)
    val entry = ZipEntry("mimetype").apply {
        method = ZipEntry.STORED
        size = bytes.size.toLong()
        compressedSize = bytes.size.toLong()
        this.crc = crc.value
    }
    zip.putNextEntry(entry)
    zip.write(bytes)
    zip.closeEntry()
}

private fun writeEntry(zip: ZipOutputStream, path: String, content: String) {
    zip.putNextEntry(ZipEntry(path))
    zip.write(content.toByteArray(Charsets.UTF_8))
    zip.closeEntry()
}

private fun epubContainerXml(): String = buildString {
    appendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
    appendLine("<container version=\"1.0\" xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\">")
    appendLine("  <rootfiles>")
    appendLine("    <rootfile full-path=\"OEBPS/content.opf\" media-type=\"application/oebps-package+xml\"/>")
    appendLine("  </rootfiles>")
    appendLine("</container>")
}

private fun epubContentOpf(
    bookTitle: String,
    uuid: String,
    timestamp: String,
    chapters: List<EpubVideoChapter>
): String = buildString {
    appendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
    appendLine("<package xmlns=\"http://www.idpf.org/2007/opf\" unique-identifier=\"BookId\" version=\"2.0\">")
    appendLine("  <metadata xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:opf=\"http://www.idpf.org/2007/opf\">")
    appendLine("    <dc:identifier id=\"BookId\">urn:uuid:$uuid</dc:identifier>")
    appendLine("    <dc:title>${escapeXml(bookTitle)}</dc:title>")
    appendLine("    <dc:language>en</dc:language>")
    appendLine("    <dc:creator>YtReader</dc:creator>")
    appendLine("    <dc:date>$timestamp</dc:date>")
    appendLine("  </metadata>")
    appendLine("  <manifest>")
    appendLine("    <item id=\"ncx\" href=\"toc.ncx\" media-type=\"application/x-dtbncx+xml\"/>")
    appendLine("    <item id=\"style\" href=\"Style/style.css\" media-type=\"text/css\"/>")
    chapters.forEachIndexed { videoIndex, chapter ->
        chapter.tracks.forEachIndexed { trackIndex, _ ->
            val id = "chapter_${videoIndex}_${trackIndex}"
            appendLine("    <item id=\"$id\" href=\"Text/$id.xhtml\" media-type=\"application/xhtml+xml\"/>")
        }
    }
    appendLine("  </manifest>")
    appendLine("  <spine toc=\"ncx\">")
    chapters.forEachIndexed { videoIndex, chapter ->
        chapter.tracks.forEachIndexed { trackIndex, _ ->
            appendLine("    <itemref idref=\"chapter_${videoIndex}_${trackIndex}\"/>")
        }
    }
    appendLine("  </spine>")
    appendLine("</package>")
}

private fun epubTocNcx(
    bookTitle: String,
    uuid: String,
    chapters: List<EpubVideoChapter>
): String = buildString {
    var playOrder = 1
    appendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
    appendLine("<ncx xmlns=\"http://www.daisy.org/z3986/2005/ncx/\" version=\"2005-1\">")
    appendLine("  <head>")
    appendLine("    <meta name=\"dtb:uid\" content=\"urn:uuid:$uuid\"/>")
    appendLine("    <meta name=\"dtb:depth\" content=\"1\"/>")
    appendLine("    <meta name=\"dtb:totalPageCount\" content=\"0\"/>")
    appendLine("    <meta name=\"dtb:maxPageNumber\" content=\"0\"/>")
    appendLine("  </head>")
    appendLine("  <docTitle><text>${escapeXml(bookTitle)}</text></docTitle>")
    appendLine("  <navMap>")
    chapters.forEach { chapter ->
        chapter.tracks.forEachIndexed { trackIndex, track ->
            val id = "chapter_${chapters.indexOf(chapter)}_${trackIndex}"
            val label = if (chapter.tracks.size > 1) {
                "${chapter.title} (${track.languageCode.uppercase()})"
            } else {
                chapter.title
            }
            appendLine("    <navPoint id=\"nav_$id\" playOrder=\"${playOrder++}\">")
            appendLine("      <navLabel><text>${escapeXml(label)}</text></navLabel>")
            appendLine("      <content src=\"Text/$id.xhtml\"/>")
            appendLine("    </navPoint>")
        }
    }
    appendLine("  </navMap>")
    appendLine("</ncx>")
}

private fun epubCss(): String = buildString {
    appendLine("body { font-family: serif; margin: 1em; line-height: 1.6; }")
    appendLine("h1 { font-size: 1.4em; margin-bottom: 0.3em; page-break-before: always; }")
    appendLine("h1:first-of-type { page-break-before: avoid; }")
    appendLine("h2 { font-size: 1.1em; margin-top: 1em; margin-bottom: 0.3em; }")
    appendLine(".metadata { color: #666; font-size: 0.9em; margin-bottom: 1em; }")
    appendLine(".metadata p { margin: 0.2em 0; }")
    appendLine(".highlight-red { background-color: #ffcccc; }")
    appendLine(".highlight-blue { background-color: #cce5ff; }")
    appendLine(".highlight-green { background-color: #ccffcc; }")
    appendLine(".highlight-yellow { background-color: #ffffcc; }")
    appendLine(".bookmark { font-weight: bold; color: #333; }")
    appendLine("p { margin: 0.5em 0; }")
}

private fun epubChapterXhtml(
    chapter: EpubVideoChapter,
    track: EpubTrackChapter,
    mode: EpubExportMode
): String = buildString {
    appendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
    appendLine("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">")
    appendLine("<html xmlns=\"http://www.w3.org/1999/xhtml\">")
    appendLine("<head>")
    appendLine("  <title>${escapeXml(chapter.title)}</title>")
    appendLine("  <link rel=\"stylesheet\" type=\"text/css\" href=\"../Style/style.css\"/>")
    appendLine("</head>")
    appendLine("<body>")

    val trackLabel = if (chapter.tracks.size > 1) {
        "${chapter.title} (${track.languageCode.uppercase()})"
    } else {
        chapter.title
    }
    appendLine("  <h1>${escapeHtml(trackLabel)}</h1>")
    appendLine("  <div class=\"metadata\">")
    if (chapter.channelName.isNotBlank()) {
        appendLine("    <p>${escapeHtml(chapter.channelName)}</p>")
    }
    if (chapter.uploadDate > 0L) {
        val dateStr = SimpleDateFormat("MMM d, yyyy", Locale.getDefault())
            .format(Date(chapter.uploadDate))
        appendLine("    <p>${escapeHtml(dateStr)}</p>")
    }
    if (chapter.videoUrl.isNotBlank()) {
        appendLine("    <p><a href=\"${escapeHtml(chapter.videoUrl)}\">${escapeHtml(chapter.videoUrl)}</a></p>")
    }
    appendLine("  </div>")

    if (mode == EpubExportMode.ANNOTATED && track.bookmarks.isNotEmpty()) {
        appendLine("  <h2>Bookmarks</h2>")
        track.bookmarks.forEach { bookmark ->
            appendLine("  <p class=\"bookmark\">${escapeHtml(bookmark.title)}</p>")
        }
    }

    appendLine("  <div>")
    if (mode == EpubExportMode.ANNOTATED && track.highlights.isNotEmpty()) {
        val annotatedText = applyEpubHighlights(track.text, track.highlights, track.notes)
        annotatedText.split("\n\n").forEach { paragraph ->
            if (paragraph.isNotBlank()) {
                appendLine("    <p>$paragraph</p>")
            }
        }
    } else {
        track.text.split("\n\n").forEach { paragraph ->
            if (paragraph.isNotBlank()) {
                appendLine("    <p>${escapeHtml(paragraph)}</p>")
            }
        }
    }
    appendLine("  </div>")

    appendLine("</body>")
    appendLine("</html>")
}

private fun applyEpubHighlights(
    text: String,
    highlights: List<TextHighlight>,
    notes: List<com.deedeedev.ytreader.data.local.HighlightNoteEntity>
): String {
    if (highlights.isEmpty()) return escapeHtml(text)
    val sorted = highlights.sortedBy { it.start }
    val result = StringBuilder()
    var lastEnd = 0
    for (highlight in sorted) {
        val start = highlight.start.coerceAtMost(text.length)
        val end = highlight.end.coerceAtMost(text.length)
        if (start > lastEnd) {
            result.append(escapeHtml(text.substring(lastEnd, start)))
        }
        if (start < end) {
            val colorClass = "highlight-${highlight.color.name.lowercase()}"
            val highlightedText = escapeHtml(text.substring(start, end))
            val matchingNote = notes.find { note ->
                note.highlightStart == highlight.start && note.highlightEnd == highlight.end
            }
            if (matchingNote != null && matchingNote.noteText.isNotBlank()) {
                result.append("<span class=\"$colorClass\" title=\"${escapeHtml(matchingNote.noteText)}\">$highlightedText</span>")
            } else {
                result.append("<span class=\"$colorClass\">$highlightedText</span>")
            }
        }
        lastEnd = end.coerceAtLeast(lastEnd)
    }
    if (lastEnd < text.length) {
        result.append(escapeHtml(text.substring(lastEnd)))
    }
    return result.toString()
}

private fun escapeHtml(text: String): String = text
    .replace("&", "&amp;")
    .replace("<", "&lt;")
    .replace(">", "&gt;")
    .replace("\"", "&quot;")
    .replace("'", "&#39;")

private fun escapeXml(text: String): String = escapeHtml(text)

private fun sanitizeEpubFileName(value: String): String {
    return value
        .replace(Regex("[^A-Za-z0-9._-]+"), "-")
        .trim('-')
        .take(60)
        .ifBlank { "export" }
}
