package com.deedeedev.ytreader.data

import com.deedeedev.ytreader.data.local.LibraryVideoRow
import com.deedeedev.ytreader.data.local.SubtitleDao
import com.deedeedev.ytreader.data.local.SubtitleEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext

class SubtitleRepository(private val subtitleDao: SubtitleDao) {

    fun observeAll(): Flow<List<SubtitleEntity>> = subtitleDao.getAll()

    fun observeLibraryChannels(): Flow<List<String>> = subtitleDao.observeLibraryChannels()

    fun observeLibraryVideoRows(
        channelName: String?,
        sortOption: String,
        isAscending: Boolean
    ): Flow<List<LibraryVideoRow>> = subtitleDao.observeLibraryVideoRows(channelName, sortOption, isAscending)

    fun observeCollectionVideoRows(
        videoIds: List<String>,
        channelName: String?,
        sortOption: String,
        isAscending: Boolean
    ): Flow<List<LibraryVideoRow>> = subtitleDao.observeCollectionVideoRows(videoIds, channelName, sortOption, isAscending)

    fun observeCollectionChannels(videoIds: List<String>): Flow<List<String>> =
        subtitleDao.observeCollectionChannels(videoIds)

    fun observeSubtitleTracksForVideos(videoIds: List<String>): Flow<List<SubtitleEntity>> =
        subtitleDao.observeSubtitleTracksForVideos(videoIds)

    fun observeCollectionVideoCount(videoIds: List<String>): Flow<Int> =
        subtitleDao.observeCollectionVideoCount(videoIds)

    fun observeById(id: Long): Flow<SubtitleEntity?> = subtitleDao.observeById(id)

    fun observeByVideoId(videoId: String): Flow<List<SubtitleEntity>> = subtitleDao.observeByVideoId(videoId)

    fun observeAllAccessibleSubtitles(): Flow<List<SubtitleEntity>> = subtitleDao.observeAllAccessibleSubtitles()

    suspend fun getById(id: Long): SubtitleEntity? = withContext(Dispatchers.IO) {
        subtitleDao.getById(id)
    }

    suspend fun getPreferredSubtitleForVideo(videoId: String): SubtitleEntity? = withContext(Dispatchers.IO) {
        subtitleDao.getPreferredSubtitleForVideo(videoId)
    }

    suspend fun countByVideoId(videoId: String): Int = withContext(Dispatchers.IO) {
        subtitleDao.countByVideoId(videoId)
    }

    suspend fun insertIgnore(subtitle: SubtitleEntity): Long = withContext(Dispatchers.IO) {
        subtitleDao.insertIgnore(subtitle)
    }

    suspend fun upsertByIdentity(subtitle: SubtitleEntity): Long = withContext(Dispatchers.IO) {
        subtitleDao.upsertByIdentity(subtitle)
    }

    suspend fun getByIdentity(videoId: String, trackIdentity: String): SubtitleEntity? = withContext(Dispatchers.IO) {
        subtitleDao.getByIdentity(videoId, trackIdentity)
    }

    suspend fun delete(subtitle: SubtitleEntity) = withContext(Dispatchers.IO) {
        subtitleDao.delete(subtitle)
    }

    suspend fun updateDownloadedSubtitle(
        id: Long,
        videoUrl: String,
        title: String,
        channelName: String,
        languageCode: String,
        subtitleTrackId: String?,
        trackIdentity: String,
        isAutoGenerated: Boolean,
        content: String,
        createdAt: Long,
        uploadDate: Long,
        fontSize: Float,
        fontFamily: String
    ) = withContext(Dispatchers.IO) {
        subtitleDao.updateDownloadedSubtitle(
            id, videoUrl, title, channelName, languageCode, subtitleTrackId,
            trackIdentity, isAutoGenerated, content, createdAt, uploadDate, fontSize, fontFamily
        )
    }

    suspend fun updateLastTimestamp(id: Long, timestamp: Long) = withContext(Dispatchers.IO) {
        subtitleDao.updateLastTimestamp(id, timestamp)
    }

    suspend fun updateLastOpenedAt(id: Long, openedAt: Long) = withContext(Dispatchers.IO) {
        subtitleDao.updateLastOpenedAt(id, openedAt)
    }

    suspend fun replaceContentForRedownload(id: Long, content: String, createdAt: Long) = withContext(Dispatchers.IO) {
        subtitleDao.replaceContentForRedownload(id, content, createdAt)
    }

    suspend fun resetReadingProgressForVideo(videoId: String) = withContext(Dispatchers.IO) {
        subtitleDao.resetReadingProgressForVideo(videoId)
    }

    suspend fun markVideoAsRead(videoId: String) = withContext(Dispatchers.IO) {
        subtitleDao.markVideoAsRead(videoId)
    }

    suspend fun deleteByVideoId(videoId: String) = withContext(Dispatchers.IO) {
        subtitleDao.deleteByVideoId(videoId)
    }

    suspend fun getMostRecentlyOpened(): SubtitleEntity? = withContext(Dispatchers.IO) {
        subtitleDao.getMostRecentlyOpened()
    }

    suspend fun updateLibraryVisibility(videoId: String, isInLibrary: Boolean) = withContext(Dispatchers.IO) {
        subtitleDao.updateLibraryVisibility(videoId, isInLibrary)
    }

    suspend fun updateHighlights(subtitleId: Long, highlights: String) = withContext(Dispatchers.IO) {
        subtitleDao.updateHighlights(subtitleId, highlights)
    }

    suspend fun updateLastStudyScroll(subtitleId: Long, scrollPosition: Int) = withContext(Dispatchers.IO) {
        subtitleDao.updateLastStudyScroll(subtitleId, scrollPosition)
    }

    suspend fun updateReadingProgress(subtitleId: Long, percent: Int, currentPage: Int, totalPages: Int) = withContext(Dispatchers.IO) {
        subtitleDao.updateReadingProgress(subtitleId, percent, currentPage, totalPages)
    }

    suspend fun updateFontSize(subtitleId: Long, fontSize: Float) = withContext(Dispatchers.IO) {
        subtitleDao.updateFontSize(subtitleId, fontSize)
    }

    suspend fun updateFontFamily(subtitleId: Long, fontFamily: String) = withContext(Dispatchers.IO) {
        subtitleDao.updateFontFamily(subtitleId, fontFamily)
    }

    suspend fun updateStudyContent(subtitleId: Long, studyContent: String) = withContext(Dispatchers.IO) {
        subtitleDao.updateStudyContent(subtitleId, studyContent)
    }

    suspend fun markAiCleaningQueued(subtitleId: Long, sourceText: String, updatedAt: Long) = withContext(Dispatchers.IO) {
        subtitleDao.markAiCleaningQueued(subtitleId, sourceText, updatedAt)
    }

    suspend fun storeAiCleaningResult(subtitleId: Long, result: String, updatedAt: Long) = withContext(Dispatchers.IO) {
        subtitleDao.storeAiCleaningResult(subtitleId, result, updatedAt)
    }

    suspend fun storeAiCleaningFailure(subtitleId: Long, summary: String?, log: String?, updatedAt: Long) = withContext(Dispatchers.IO) {
        subtitleDao.storeAiCleaningFailure(subtitleId, summary, log, updatedAt)
    }

    suspend fun cancelAiCleaning(subtitleId: Long, updatedAt: Long) = withContext(Dispatchers.IO) {
        subtitleDao.cancelAiCleaning(subtitleId, updatedAt)
    }

    suspend fun clearAiCleaningResult(subtitleId: Long) = withContext(Dispatchers.IO) {
        subtitleDao.clearAiCleaningResult(subtitleId)
    }

    suspend fun clearAiCleaningError(subtitleId: Long) = withContext(Dispatchers.IO) {
        subtitleDao.clearAiCleaningError(subtitleId)
    }

    suspend fun countLibraryEntriesByVideoId(videoId: String): Int = withContext(Dispatchers.IO) {
        subtitleDao.countLibraryEntriesByVideoId(videoId)
    }

    suspend fun getLibraryVideoIds(): List<String> = withContext(Dispatchers.IO) {
        subtitleDao.getLibraryVideoIds()
    }
}
