package com.deedeedev.ytreader

import android.content.Context
import androidx.room.Room
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.deedeedev.ytreader.data.UserPreferencesRepository
import com.deedeedev.ytreader.data.YoutubeRepository
import com.deedeedev.ytreader.data.AiCleaningRepository
import com.deedeedev.ytreader.data.local.AppDatabase
import com.deedeedev.ytreader.data.local.SubtitleDao

import com.deedeedev.ytreader.data.remote.NewPipeDownloader
import okhttp3.OkHttpClient
import org.schabi.newpipe.extractor.NewPipe
import java.util.concurrent.TimeUnit

interface AppContainer {
    val subtitleDao: SubtitleDao
    val youtubeRepository: YoutubeRepository
    val userPreferencesRepository: UserPreferencesRepository
    val aiCleaningRepository: AiCleaningRepository
}

class DefaultAppContainer(private val context: Context) : AppContainer {
    private val MIGRATION_5_6 = Migration(5, 6) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN studyContent TEXT")
    }

    private val MIGRATION_6_7 = Migration(6, 7) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN highlights TEXT NOT NULL DEFAULT ''")
    }

    private val MIGRATION_7_8 = Migration(7, 8) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN subtitleTrackId TEXT")
        database.execSQL(
            "ALTER TABLE subtitles ADD COLUMN isAutoGenerated INTEGER NOT NULL DEFAULT 0"
        )
    }

    private val MIGRATION_8_9 = Migration(8, 9) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN lastStudyScroll INTEGER NOT NULL DEFAULT 0")
    }

    private val MIGRATION_9_10 = Migration(9, 10) { database ->
        database.execSQL(
            "ALTER TABLE subtitles ADD COLUMN aiCleaningInProgress INTEGER NOT NULL DEFAULT 0"
        )
        database.execSQL("ALTER TABLE subtitles ADD COLUMN aiCleaningSourceText TEXT")
        database.execSQL("ALTER TABLE subtitles ADD COLUMN aiCleaningPendingResult TEXT")
        database.execSQL("ALTER TABLE subtitles ADD COLUMN aiCleaningErrorSummary TEXT")
        database.execSQL("ALTER TABLE subtitles ADD COLUMN aiCleaningErrorLog TEXT")
        database.execSQL(
            "ALTER TABLE subtitles ADD COLUMN aiCleaningUpdatedAt INTEGER NOT NULL DEFAULT 0"
        )
    }

    private val MIGRATION_10_11 = Migration(10, 11) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN lastOpenedAt INTEGER NOT NULL DEFAULT 0")
    }

    private val database: AppDatabase by lazy {
        Room.databaseBuilder(
            context.applicationContext,
            AppDatabase::class.java,
            "ytreader.db"
        )
        .addMigrations(
            MIGRATION_5_6,
            MIGRATION_6_7,
            MIGRATION_7_8,
            MIGRATION_8_9,
            MIGRATION_9_10,
            MIGRATION_10_11
        )
        .fallbackToDestructiveMigration(false)
        .build()
    }

    private val okHttpClient: OkHttpClient by lazy {
        OkHttpClient.Builder().build()
    }

    private val aiOkHttpClient: OkHttpClient by lazy {
        OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(120, TimeUnit.SECONDS)
            .callTimeout(150, TimeUnit.SECONDS)
            .build()
    }

    init {
        NewPipe.init(NewPipeDownloader(okHttpClient))
    }

    override val subtitleDao: SubtitleDao by lazy {
        database.subtitleDao()
    }

    override val youtubeRepository: YoutubeRepository by lazy {
        YoutubeRepository(okHttpClient)
    }

    override val userPreferencesRepository: UserPreferencesRepository by lazy {
        UserPreferencesRepository(context)
    }

    override val aiCleaningRepository: AiCleaningRepository by lazy {
        AiCleaningRepository(aiOkHttpClient)
    }
}
