package com.deedeedev.ytreader

import android.content.Context
import androidx.room.Room
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.deedeedev.ytreader.data.UserPreferencesRepository
import com.deedeedev.ytreader.data.YoutubeRepository
import com.deedeedev.ytreader.data.AiCleaningRepository
import com.deedeedev.ytreader.data.local.AppDatabase
import com.deedeedev.ytreader.data.local.SubtitleDao
import com.deedeedev.ytreader.domain.SubtitleIdentity
import com.deedeedev.ytreader.domain.YouTubeVideoIdNormalizer

import com.deedeedev.ytreader.data.remote.NewPipeDownloader
import okhttp3.OkHttpClient
import org.schabi.newpipe.extractor.NewPipe
import java.util.concurrent.TimeUnit

interface AppContainer {
    val subtitleDao: SubtitleDao
    val youtubeRepository: YoutubeRepository
    val userPreferencesRepository: UserPreferencesRepository
    val aiCleaningRepository: AiCleaningRepository
}

class DefaultAppContainer(private val context: Context) : AppContainer {
    private val MIGRATION_5_6 = Migration(5, 6) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN studyContent TEXT")
    }

    private val MIGRATION_6_7 = Migration(6, 7) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN highlights TEXT NOT NULL DEFAULT ''")
    }

    private val MIGRATION_7_8 = Migration(7, 8) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN subtitleTrackId TEXT")
        database.execSQL(
            "ALTER TABLE subtitles ADD COLUMN isAutoGenerated INTEGER NOT NULL DEFAULT 0"
        )
    }

    private val MIGRATION_8_9 = Migration(8, 9) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN lastStudyScroll INTEGER NOT NULL DEFAULT 0")
    }

    private val MIGRATION_9_10 = Migration(9, 10) { database ->
        database.execSQL(
            "ALTER TABLE subtitles ADD COLUMN aiCleaningInProgress INTEGER NOT NULL DEFAULT 0"
        )
        database.execSQL("ALTER TABLE subtitles ADD COLUMN aiCleaningSourceText TEXT")
        database.execSQL("ALTER TABLE subtitles ADD COLUMN aiCleaningPendingResult TEXT")
        database.execSQL("ALTER TABLE subtitles ADD COLUMN aiCleaningErrorSummary TEXT")
        database.execSQL("ALTER TABLE subtitles ADD COLUMN aiCleaningErrorLog TEXT")
        database.execSQL(
            "ALTER TABLE subtitles ADD COLUMN aiCleaningUpdatedAt INTEGER NOT NULL DEFAULT 0"
        )
    }

    private val MIGRATION_10_11 = Migration(10, 11) { database ->
        database.execSQL("ALTER TABLE subtitles ADD COLUMN lastOpenedAt INTEGER NOT NULL DEFAULT 0")
    }

    private val MIGRATION_11_12 = Migration(11, 12) { database ->
        database.execSQL(
            """
            CREATE TABLE IF NOT EXISTS subtitles_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                videoId TEXT NOT NULL,
                videoUrl TEXT NOT NULL,
                title TEXT NOT NULL,
                channelName TEXT NOT NULL,
                languageCode TEXT NOT NULL,
                subtitleTrackId TEXT,
                isAutoGenerated INTEGER NOT NULL,
                trackIdentity TEXT NOT NULL,
                content TEXT NOT NULL,
                studyContent TEXT,
                lastTimestamp INTEGER NOT NULL,
                lastOpenedAt INTEGER NOT NULL,
                lastStudyScroll INTEGER NOT NULL,
                fontSize REAL NOT NULL,
                createdAt INTEGER NOT NULL,
                uploadDate INTEGER NOT NULL,
                fontFamily TEXT NOT NULL,
                highlights TEXT NOT NULL,
                aiCleaningInProgress INTEGER NOT NULL,
                aiCleaningSourceText TEXT,
                aiCleaningPendingResult TEXT,
                aiCleaningErrorSummary TEXT,
                aiCleaningErrorLog TEXT,
                aiCleaningUpdatedAt INTEGER NOT NULL
            )
            """.trimIndent()
        )
        database.execSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS index_subtitles_new_videoId_trackIdentity ON subtitles_new(videoId, trackIdentity)"
        )

        val cursor = database.query(
            """
            SELECT id, videoId, title, channelName, languageCode, subtitleTrackId, isAutoGenerated,
                   content, studyContent, lastTimestamp, lastOpenedAt, lastStudyScroll, fontSize,
                   createdAt, uploadDate, fontFamily, highlights, aiCleaningInProgress,
                   aiCleaningSourceText, aiCleaningPendingResult, aiCleaningErrorSummary,
                   aiCleaningErrorLog, aiCleaningUpdatedAt
            FROM subtitles
            ORDER BY createdAt DESC, id DESC
            """.trimIndent()
        )

        val statement = database.compileStatement(
            """
            INSERT OR IGNORE INTO subtitles_new (
                id, videoId, videoUrl, title, channelName, languageCode, subtitleTrackId,
                isAutoGenerated, trackIdentity, content, studyContent, lastTimestamp,
                lastOpenedAt, lastStudyScroll, fontSize, createdAt, uploadDate, fontFamily,
                highlights, aiCleaningInProgress, aiCleaningSourceText, aiCleaningPendingResult,
                aiCleaningErrorSummary, aiCleaningErrorLog, aiCleaningUpdatedAt
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """.trimIndent()
        )

        cursor.use {
            while (it.moveToNext()) {
                val legacyVideoId = it.getString(it.getColumnIndexOrThrow("videoId"))
                val languageCode = it.getString(it.getColumnIndexOrThrow("languageCode"))
                val subtitleTrackId = it.getNullableString("subtitleTrackId")
                val isAutoGenerated = it.getInt(it.getColumnIndexOrThrow("isAutoGenerated")) != 0
                val canonicalVideoRef = YouTubeVideoIdNormalizer.canonicalize(legacyVideoId)
                val trackIdentity = SubtitleIdentity.fromTrack(
                    subtitleTrackId = subtitleTrackId,
                    languageCode = languageCode,
                    isAutoGenerated = isAutoGenerated
                )

                statement.clearBindings()
                statement.bindLong(1, it.getLong(it.getColumnIndexOrThrow("id")))
                statement.bindString(2, canonicalVideoRef.videoId)
                statement.bindString(3, canonicalVideoRef.videoUrl)
                statement.bindString(4, it.getString(it.getColumnIndexOrThrow("title")))
                statement.bindString(5, it.getString(it.getColumnIndexOrThrow("channelName")))
                statement.bindString(6, languageCode)
                if (subtitleTrackId == null) {
                    statement.bindNull(7)
                } else {
                    statement.bindString(7, subtitleTrackId)
                }
                statement.bindLong(8, if (isAutoGenerated) 1L else 0L)
                statement.bindString(9, trackIdentity)
                statement.bindString(10, it.getString(it.getColumnIndexOrThrow("content")))
                bindNullableString(statement = statement, index = 11, value = it.getNullableString("studyContent"))
                statement.bindLong(12, it.getLong(it.getColumnIndexOrThrow("lastTimestamp")))
                statement.bindLong(13, it.getLong(it.getColumnIndexOrThrow("lastOpenedAt")))
                statement.bindLong(14, it.getLong(it.getColumnIndexOrThrow("lastStudyScroll")))
                statement.bindDouble(15, it.getDouble(it.getColumnIndexOrThrow("fontSize")))
                statement.bindLong(16, it.getLong(it.getColumnIndexOrThrow("createdAt")))
                statement.bindLong(17, it.getLong(it.getColumnIndexOrThrow("uploadDate")))
                statement.bindString(18, it.getString(it.getColumnIndexOrThrow("fontFamily")))
                statement.bindString(19, it.getString(it.getColumnIndexOrThrow("highlights")))
                statement.bindLong(20, it.getLong(it.getColumnIndexOrThrow("aiCleaningInProgress")))
                bindNullableString(statement = statement, index = 21, value = it.getNullableString("aiCleaningSourceText"))
                bindNullableString(statement = statement, index = 22, value = it.getNullableString("aiCleaningPendingResult"))
                bindNullableString(statement = statement, index = 23, value = it.getNullableString("aiCleaningErrorSummary"))
                bindNullableString(statement = statement, index = 24, value = it.getNullableString("aiCleaningErrorLog"))
                statement.bindLong(25, it.getLong(it.getColumnIndexOrThrow("aiCleaningUpdatedAt")))
                statement.executeInsert()
            }
        }

        database.execSQL("DROP TABLE subtitles")
        database.execSQL("ALTER TABLE subtitles_new RENAME TO subtitles")
        database.execSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS index_subtitles_videoId_trackIdentity ON subtitles(videoId, trackIdentity)"
        )
    }

    private val database: AppDatabase by lazy {
        Room.databaseBuilder(
            context.applicationContext,
            AppDatabase::class.java,
            "ytreader.db"
        )
        .addMigrations(
            MIGRATION_5_6,
            MIGRATION_6_7,
            MIGRATION_7_8,
            MIGRATION_8_9,
            MIGRATION_9_10,
            MIGRATION_10_11,
            MIGRATION_11_12
        )
        .fallbackToDestructiveMigration(false)
        .build()
    }

    private val okHttpClient: OkHttpClient by lazy {
        OkHttpClient.Builder().build()
    }

    private val aiOkHttpClient: OkHttpClient by lazy {
        OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(120, TimeUnit.SECONDS)
            .callTimeout(150, TimeUnit.SECONDS)
            .build()
    }

    init {
        NewPipe.init(NewPipeDownloader(okHttpClient))
    }

    override val subtitleDao: SubtitleDao by lazy {
        database.subtitleDao()
    }

    override val youtubeRepository: YoutubeRepository by lazy {
        YoutubeRepository(okHttpClient)
    }

    override val userPreferencesRepository: UserPreferencesRepository by lazy {
        UserPreferencesRepository(context)
    }

    override val aiCleaningRepository: AiCleaningRepository by lazy {
        AiCleaningRepository(aiOkHttpClient)
    }

    companion object {
        private fun android.database.Cursor.getNullableString(columnName: String): String? {
            val index = getColumnIndexOrThrow(columnName)
            return if (isNull(index)) null else getString(index)
        }

        private fun bindNullableString(
            statement: androidx.sqlite.db.SupportSQLiteStatement,
            index: Int,
            value: String?
        ) {
            if (value == null) {
                statement.bindNull(index)
            } else {
                statement.bindString(index, value)
            }
        }
    }
}
